import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, orders, profit, sales,
}: Readonly<{
  children: React.ReactNode;
  orders: React.ReactNode;
  profit: React.ReactNode;
  sales: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
        <div className="text-center py-3"><Link href="/dashboard/details"> Go To Order Details </Link></div>
        <div className="flex gap-3 my-3 justify-center">
          {orders}
          {profit}
          {sales}
        </div>
        <div className="text-center">
        {children}
        </div>
      </body>
    </html>
  );
}
